web:
    image: hitalos/laravel:latest
    container_name: begaming
    ports:
        - 8585:80
    volumes:
        - ./:/var/www
    links:
        - db
db:
  image: mysql:5.7
  restart: always
  environment: 
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  ports:
    - 3306:3306
  expose:
    - 3306
  volumes:
    - my-db:/var/lib/mysql